

---
version: 1.0.0
recipes:
- link: recipes/guest_checkout.md
  title: How to Make a Guest Checkout
  type: recipe
- link: recipes/vault_credit_card_gift_card.md
  title: How to Vault a Credtit Card or Gift Card
  type: recipe
  - link: recipes/duplicate_transactions.md
  title: How to Avoid a Duplicate Transaction 
  type: recipe
- link: recipes/Recipe-2.md
  title: Payment with Py
  type: recipe
- link: recipes/Recipe-3.md
  title: Payment with Rust
  type: recipe
- link: recipes/Recipe-4.md
  title: Payment with Java
  type: recipe

