version: 1.0.0
recipes:
- link: recipes/LandingPage.md
  type: recipe
- link: recipes/customerRegistration.md
  title: How to Create, Read, Update, and Delete a Customer Profile
  type: recipe
- link: recipes/guest_checkout.md
  title: How to Make a Guest Checkout
  type: recipe
- link: recipes/vault_credit_card_gift_card.md
  title: How to Vault a Credit Card or Gift Card 
  type: recipe
- link: recipes/duplicate_transactions.md
  title: How to Avoid a Duplicate Transaction 
  type: recipe
- link: recipes/Paypal_Venmo_guide.md
  title: How to Make a Payment with Paypal or Venmo
  type: recipe
- link: recipes/Split_Tender_Payment.md
  title: How to Make a split Payment 
  type: recipe
- link: recipes/InApp_Payments.md
  title: How to Make a InApp Payments 
  type: recipe
- link: recipes/refunds.md
  title: How to Issue a Refund
  type: recipe
