################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates.
# Fiserv is a trademark of Fiserv, Inc.,
# registered or used in the United States and foreign countries,
# and may or may not be registered in your country.
# All trademarks, service marks,
# and trade names referenced in this
# material are the property of their
# respective owners. This work, including its contents
# and programming, is confidential and its use
# is strictly limited. This work is furnished only
# for use by duly authorized licensees of Fiserv, Inc.
# or its affiliates, and their designated agents
# or employees responsible for installation or
# operation of the products. Any other use,
# duplication, or dissemination without the
# prior written consent of Fiserv, Inc.
# or its affiliates is strictly prohibited.
# Except as specified by the agreement under
# which the materials are furnished, Fiserv, Inc.
# and its affiliates do not accept any liabilities
# with respect to the information contained herein
# and are not responsible for any direct, indirect,
# special, consequential or exemplary damages
# resulting from the use of this information.
# No warranties, either express or implied,
# are granted or extended by this work or
# the delivery of this work
################################################################################
- sections:
    - title: Will restructure this
      link:
      open: true
      sections:
        - title: Account Services
          link: 
          open:
          sections:
            - title: Retrieve Token & Encryption Key
              link:
            - title: Tokenize an Account
              link:
            - title: Tokenize an Account with Nonce
              link:
            - title: Vault an Account
              link:
            - title: Get a List of Accounts
              link:
            - title: Get Account Details
              link:
            - title: Update a Vaulted Account
              link:
            - title: Delete a Vaulted Account
              link:
            - title: Retrieve an Account with a Nonce Token
              link:
        - title: Customer Services
          link:
          open:
          sections:
            - title: Create an Account
              link:
            - title: Update an Account
              link:
            - title: Delete an Account
              link:
            - title: Get all Accounts
              link:
            - title: Get Account Details
              link:

