################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productName: Connected Commerce (uCom)
  productionDescription: Connected Commerce (uCom) Items
  whoIsItFor: REPLACEME
  image: 
    link: "/assets/images/Fiserv_Logo.jpg"
    altText: uCom
featuredFeatures:
  - title: Secure Payment Card Collections 
    description:  Wide variety of options to integrate your solution with us. Server to server, Native API's, CORS support and finally Hosted Pages are all offerings we support.
    tags: ["Payments", "uCom", "server to server", "native API", "Hosted Pages", "CORS",]
    bullets: ["REPLACEME", "REPLACEME" ]  
  - title: Tokenization 
    description:  Wide range of support with payment tokens. This includes Fiserv issued, third party and gateway specific for your token related needs. 
    tags: ["Tokens", "uCom", "gateway"]
    bullets: ["REPLACEME", "REPLACEME" ]  
    relatedDocs:
  - title: Wide range of payment support 
    description: Traditional card support with addition to private label, EBT, Fleet and Cardnet are just some of the thirteen types of cards we support
    tags: ["Tokenization", "uCom", "EBT", "Fleet", "visa", "mc", "cardnet", "american express", "discover", "diners club", "private label", "jcb", "union pay", "EBT Snap", "EBT Cash" ]
    bullets: ["REPLACEME", "REPLACEME" ]  
    relatedDocs:
  - title: Gift Solutions 
    description: From redemption, reload to purchase the team can support gift card use for merchants. Balance, history and balance merges are all something that is supported. 
    tags: ["Gift", "uCom"]
    bullets: ["REPLACEME", "REPLACEME" ]  
    relatedDocs:
      - relatedDoc: 
        title: REPLACEME
        description: REPLACEME
        link: ./docs/REPLACE-ME1.md
      - relatedDoc: 
        title: REPLACEME
        description: REPLACEME
        link: ./docs/REPLACE-ME2.md
      - relatedDoc: 
        title: REPLACEME
        description: REPLACEME
        link: ./docs/REPLACE-ME3.md
    relatedAPIs:
      - relatedAPI: 
        title: REPLACEME
        description: REPLACEME
        type: "patch"        
        path: "/v1/REPLACEME1"
      - relatedAPI: 
        title: REPLACEME
        description: REPLACEME
        type: "post"        
        path: "/v1/REPLACEME2"
      - relatedAPI: 
        title: REPLACEME
        description: REPLACEME
        type: "get"        
        path: "/v1/REPLACEME3"
