################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productName: Connected Commerce (uCom)
  productionDescription: Connected Commerce (uCom) brings in frictionless commerce that increases brand reach, delivers relevant & timely information to users and brings in great usability experiences in a safe & secure environment. We bring in Commerce Solutions to the new digital & connected world to meet all sorts of "Customer Expectations," "Consumer Experience," "Speed to Market" and "Set Industry Trend." Connected Commerce (uCom) acts as a mobile gateway in accepting the request from its front end (MAS, App, POS, web browser etc.) system and route them to vaulting, payment, loyalty, prepaid/gift processing etc., based on client needs. </br></br> <b> Why Connected Commerce (uCom)? </b> </br></br> Bring in a seamless customer experience and offer services across Channels; Online, Mobile & In-Store shopping Know your customer - Get a 360 degree view of customer activity across channels and serve their need from Anywhere & Everywhere. Bring in a seamless customer experience and offer services across Channels &#150; Online, Mobile & In-Store shopping Know your customer - Get a 360 degree view of customer activity across channels and serve their need from Anywhere & Everywhere. </br></br> <b> Regions we operate </b> </br></br> Connected Commerce (uCom) services are deployed across geography covering North America, EMEA and LATAM regions. </br></br> <b> What are the verticals in Connected Commerce (uCom)? </b> </br></br> We have Petro (Petroleum Industry), Quick Service Restaurants (QSR), Automobiles, Grocery, Sports Arena and Health and Wellness (H&W). </br> </br> To start integrating with Connected Commerce (uCom), please refer to our <a href="product/ConnectedCommerce/docs/?path=/docs/documentation/Standard_Implementation_Guide.md">Implementation Guide</a> section. 
  whoIsItFor: test
  image: 
    link: "/assets/images/Fiserv_Logo.jpg"
    altText: uCom
featuredFeatures:
 - title: Complex Orchestration
   description:  Ability to execute complex flows such as multi-tender payments, loyalty earning and redemptions, enterprise level balance management, etc.
   tags: ["multi tender", "uCom", "loyalty", "gateway"]
 - title: "Customer Management"
   description:  Securely collect, store and manage your customer/account details. We perform payment operations to keep you out of PCI (Payment Card Industry) scope.
   tags: ["PCI", "uCom", "secure", "gateway"]
 - title: Multi-purse Wallets 
   description: Ability to leverage various stored value accounts for enterprise clients that are tied to a customer to manage corporate level loyalty balances, CPG offers, gift balances, etc.
   tags: ["Multi Purse", "uCom", "wallets", "loyalty", "gift", "balances", "gateway"]
 - title: "Site Management"
   description: Expertise to manage franchise and corporate locations. Automated onboarding and maintenance is used to support enterprise clients.
   tags: ["site management", "uCom", "gateway"]
 - title: Secure Card Collections
   description: Wide variety of options to integrate your solution with us. Server to server, Native API's, CORS support and Hosted Pages are all supported offerings.
   tags: ["Server to Server", "CORS","Native API", "uCom", "gateway"]
 - title: Tokenization
   description: Various types of payment tokens such as Fiserv issued, third party and gateway specific for your token related needs.
   tags: ["tokenization", "uCom", "gateway"]
 - title: Payment Methods
   description: In addition to traditional credit card support, we enable many alternate payment methods such as gift cards, PayPal, Venmo, ApplePay, GooglePay, private label, EBT, Fleet, etc.
   tags: ["Payments","Paypal","uCom", "venmo", "applepay", "GooglePay", "private label", "EBT", "Fleet", "gift cards", "gateway"]
 - title: Fraud Prevention
   description: Core fraud prevention tools with velocity rules around Amount limits, IP restrictions, etc. In addition, 3rd party fraud partners with device intelligence is supported.
   tags: ["fraud","3rd Party", "uCom", "device intelligence", "gateway"]
 - title: Gift Solutions
   description: Merchants can utilize closed/open loop gift cards to support features such as redemption, reload, purchase, balance, history and balance merges.
   tags: ["Open Loop", "Closed Loop", "uCom", "gift", "gateway"]
 - title: Delivery Optimization
   description: End to end management around delivery from split settlement (corp/franchise/driver/tip/etc) to execution of delivery instructions to driver network.  Notifications of delivery timing and updates are provided to the end user and/or merchant.
   tags: ["Split Settlement","delivery services", "uCom", "gateway"]
 - title: Apply and Buy
   description: Ability for und users to apply in real-time for cards and use them for purchase in a single transaction flow.
   tags: ["Real Time", "uCom", "Apply and Buy", "gateway"]
#    - relatedDoc: 
#        title: REPLACEME
#        description: REPLACEME
#        link: ./docs/REPLACE-ME1.md
#      - relatedDoc: 
#        title: REPLACEME
#        description: REPLACEME
#        link: ./docs/REPLACE-ME2.md
#      - relatedDoc: 
#        title: REPLACEME
#        description: REPLACEME
#        link: ./docs/REPLACE-ME3.md
#    relatedAPIs:
#      - relatedAPI: 
#        title: REPLACEME
#        description: REPLACEME
#        type: "patch"        
#        path: "/v1/REPLACEME1"
#      - relatedAPI: 
#        title: REPLACEME
#        description: REPLACEME
#        type: "post"        
#        path: "/v1/REPLACEME2"
#      - relatedAPI: 
#        title: REPLACEME
#        description: REPLACEME
#        type: "get"        
#        path: "/v1/REPLACEME3"
